apiVersion: v2
name: my-go-app
description: A simple Go application to calculate the mass of a sphere or cube based on dimensions.
version: 0.1.0
appVersion: "1.0"
maintainers:
  - name: Your Name
    email: your-email@example.com
dependencies: []
